### ISSUE TITLE
Error while generating

### ISSUE THREAD

**Issue by PYUDNG** [Keytoyze/Mug-Diffusion#11]
Platform MacOS Big Sur 11.7.6
running from source
requirements installed, except
![截屏2023-05-17 下午1 36 49](https://github.com/Keytoyze/Mug-Diffusion/assets/63054558/1c4a2fda-ade9-4335-92b7-1c858479db9c)

After clicked "Start Generation" in webui for a while, I got this:
![截屏2023-05-17 上午9 57 31](https://github.com/Keytoyze/Mug-Diffusion/assets/63054558/e0f7223a-1080-4954-ad9d-a0b28a887e68)

Following the instructions "use via API" in webui footer, I made a little python script but also got the same error while generating:
[main.py.txt](https://github.com/Keytoyze/Mug-Diffusion/files/11494549/main.py.txt)

![截屏2023-05-17 下午1 36 17](https://github.com/Keytoyze/Mug-Diffusion/assets/63054558/c449a1f7-8b9e-4c88-abee-834454cf9e3f)

It seems like an webui error. Is there configuration mistake or something else?

**Comment by Keytoyze** [comment]
Do you use VPN? As reported by others this issue may result from VPN's proxy problem.

**Comment by PYUDNG** [comment]
That's the problem. After I closed my proxy and unset proxy in bash (using ```unset http_proxy``` and ```unset https_proxy```), Mug Diffusion works well! I hope my experience helps for others with the same problem. Thank you!
