### ISSUE TITLE
6k谱出不出

### ISSUE THREAD

**Issue by kevinchang214** [Keytoyze/Mug-Diffusion#19]
你好，都2024年12月了，怎么还不出6k谱选项？

**Comment by Keytoyze** [comment]
新模型支持4-8k，已经快训好了，别急

**Comment by kevinchang214** [comment]
给个确定的时间。



---原始邮件---
发件人: "C. ***@***.***&gt;
发送时间: 2024年12月3日(周二) 晚上6:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Keytoyze/Mug-Diffusion] 6k谱出不出 (Issue #19)




 
新模型支持4-8k，已经快训好了，别急

**Comment by kevinchang214** [comment]
你好？在吗？什么时候发布？

**Comment by ElainaFanBoy** [comment]
> 你好？在吗？什么时候发布？

你好，你可以加readme里的qq群关注最新动态，请不要滥用issue重复刷相同问题

**Comment by kevinchang214** [comment]
qq?没写着

**Comment by ElainaFanBoy** [comment]
> qq?没写着
> 
> 

![Screenshot_2024-12-13-15-12-41-825_com.github.android-edit.jpg](https://github.com/user-attachments/assets/7f336628-20e5-4e46-a5ab-d9e6a6fbfb1d)

**Comment by kevinchang214** [comment]
&nbsp;你倒是给我说QQ群到底在哪？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月10日(周二) 下午5:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Keytoyze/Mug-Diffusion] 6k谱出不出 (Issue #19)




  
你好？在吗？什么时候发布？
  
你好，你可以加readme里的qq群关注最新动态，请不要滥用issue重复刷相同问题

**Comment by kevinchang214** [comment]
我已加了，求申请

**Comment by kevinchang214** [comment]
我已经加群了，求申请。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月13日(周五) 下午3:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Keytoyze/Mug-Diffusion] 6k谱出不出 (Issue #19)




  
qq?没写着
  
Screenshot_2024-12-13-15-12-41-825_com.github.android-edit.jpg (view on web)

**Comment by kevinchang214** [comment]
有时间你看一下邮件



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月13日(周五) 下午3:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Keytoyze/Mug-Diffusion] 6k谱出不出 (Issue #19)




  
qq?没写着
  
Screenshot_2024-12-13-15-12-41-825_com.github.android-edit.jpg (view on web)

**Comment by kevinchang214** [comment]
你好，都2024年12月27日
了，怎么还不出6k谱选项？
