### ISSUE TITLE
Charts queing?

### ISSUE THREAD

**Issue by heipizhu4** [Keytoyze/Mug-Diffusion#5]
Sometimes I want to create charts in a row for various difficulties or songs. Would it be possible to add a queue function to make it easier to create charts more efficiently?

**Comment by Keytoyze** [comment]
Maybe you can open multiple programs to run? The queue function requires large modification on the current framework, so it's not a high priority

**Comment by heipizhu4** [comment]
> Maybe you can open multiple programs to run? The queue function requires large modification on the current framework, so it's not a high priority

Okay, I see, thanks for telling me about it (honestly I didn't think of the 'muliple program' method before LOL)
